spring:
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false

logging:
  file: /home/seven/Record/log/logback/testspringbootlog2.log
  level:
    org.springframework.web: DEBUG
    
server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: lumiseven7
    key-store-type: PKCS12
    key-alias: tomcat
    